Full db implementation
CS481/factory-express pull request #1
Opened 2021-01-23 21:50 UTC by caydenreynolds

2021-01-23 21:51 UTC, caydenreynolds commented
Mongo stuff occasionally fails, but I can't reproduce the problem consistently enough to debug it easily. We'll see if it becomes a problem

2021-01-23 23:56 UTC, ScratchnSniff0 commented on src/test/database/MongoConn.test.js
> +test("Sucessfully inserts one object", done => {
Sucessfully -> Successfully

2021-01-23 23:58 UTC, ScratchnSniff0 commented on src/test/database/MongoConn.test.js
> +test("Sucessfully executes advanced queries", done => {
Sucessfully -> Successfully

2021-01-24 00:00 UTC, ScratchnSniff0 commented on src/database/IDBConn.js
>  }
Is newline at the end of a file idiomatic for JS?

2021-01-24 00:01 UTC, ScratchnSniff0 commented on src/database/MongoConn.js
> +}
Is newline at the end of a file idiomatic for JS?

2021-01-24 00:04 UTC, ScratchnSniff0 commented on src/model/SimObj.js
> +}
Is newline at the end of a file idiomatic for JS?

2021-01-24 00:05 UTC, ScratchnSniff0 commented on src/test/database/MongoConn.test.js
> +test("Sucessfully replaces one object", done => {
Sucessfully -> Successfully

2021-01-24 00:05 UTC, ScratchnSniff0 commented on src/test/database/MongoConn.test.js
> +test("Sucessfully updates one object", done => {
Sucessfully -> Successfully

2021-01-24 00:09 UTC, ScratchnSniff0 commented on test.sh
> +#!/bin/bash
Scary! Share file personally instead?

2021-01-24 00:10 UTC, ScratchnSniff0 requested changes
Commented on a few things.  But otherwise looks good to me!

2021-01-24 22:17 UTC, rdoster13 approved these changes
Looks good to me

2021-01-25 16:48 UTC, merged